/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AI: Ai;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		VECTORIZE: VectorizeIndex;
	}
}
interface Env extends Cloudflare.Env {}
